# Generated by Django 5.2.4 on 2025-08-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Image',
            new_name='image',
        ),
    ]
